#!/usr/bin/with-contenv bashio
# Populates config/.env and config/speakers.json from the add-on's Configuration
# tab, then hands off to the same server.js every other deployment method runs.
# This is the ONLY job this wrapper does — MASS_TOKEN login, the SUPERVISOR_TOKEN
# restart cascade, and Ingress-relative fetches are all native in the app itself.

CONFIG_PATH=/app/config
ENV_FILE="${CONFIG_PATH}/.env"

# No speakers.json handling here on purpose — v4 auto-discovery (server.js)
# derives the subnet from MASS_IP and finds speakers itself on every boot.
# host_network: true in config.yaml is what gives it real LAN access to do so.

bashio::log.info "Writing config/.env from add-on options..."

# Auto-detect this host's address when app_ip is left blank — host_network:
# true means this container's "default" interface IS the HA host's real LAN
# interface, so Supervisor's own network info gives us the right answer
# without asking the user to type an IP they already told HA about.
APP_IP="$(bashio::config 'app_ip')"
APP_IP_AUTODETECTED=false
if [ -z "${APP_IP}" ]; then
    APP_IP="$(bashio::network.ipv4_address 2>/dev/null | head -n1 | cut -d'/' -f1)"
    APP_IP_AUTODETECTED=true
    bashio::log.info "app_ip not set — auto-detected host address: ${APP_IP}"
fi

# mass_ip defaults to the same host address when left blank, since the common
# case for installing this AS an HA add-on is Music Assistant running on the
# same instance. Users with MASS on a separate machine still override it.
MASS_IP="$(bashio::config 'mass_ip')"
MASS_IP_AUTODETECTED=false
if [ -z "${MASS_IP}" ]; then
    MASS_IP="${APP_IP}"
    MASS_IP_AUTODETECTED=true
    bashio::log.info "mass_ip not set — defaulting to this host's address: ${MASS_IP}"
fi

MASS_PORT="$(bashio::config 'mass_port')"
MASS_TOKEN="$(bashio::config 'mass_token')"
MASS_USERNAME="$(bashio::config 'mass_username')"
MASS_PASSWORD="$(bashio::config 'mass_password')"

{
    echo "# .env file format: v4.0"
    echo "# Auto-generated by the Home Assistant add-on wrapper on every start."
    echo "# Edit values in the add-on's Configuration tab, not this file directly."
    echo ""
    echo "APP_IP=${APP_IP}"
    echo "APP_PORT=3000"
    echo ""
    echo "MASS_IP=${MASS_IP}"
    echo "MASS_PORT=${MASS_PORT}"
    echo "MASS_TOKEN=${MASS_TOKEN}"
    echo "MASS_USERNAME=${MASS_USERNAME}"
    echo "MASS_PASSWORD=${MASS_PASSWORD}"
    echo ""
    echo "BOSE_PORT=8090"
    echo "TRUST_PROXY=true"
} > "${ENV_FILE}"

# Persist auto-detected address(es) back into this add-on's own Configuration
# tab so they show up filled in next time instead of blank. The Supervisor
# options endpoint REPLACES the whole options object rather than merging
# (POST /addons/self/options -> app.options = body["options"], no merge) —
# so every known field is resent here, not just app_ip/mass_ip, to avoid
# wiping out mass_port/mass_token/mass_username/mass_password. Best-effort:
# a failure here doesn't stop boot, since .env above is already written from
# the resolved values either way. Self-limiting: once persisted, app_ip/
# mass_ip are no longer blank on the next boot, so this block stops firing.
if [ "${APP_IP_AUTODETECTED}" = true ] || [ "${MASS_IP_AUTODETECTED}" = true ]; then
    PATCH_BODY="$(jq -n \
        --arg app_ip "${APP_IP}" \
        --arg mass_ip "${MASS_IP}" \
        --argjson mass_port "${MASS_PORT:-8095}" \
        --arg mass_token "${MASS_TOKEN}" \
        --arg mass_username "${MASS_USERNAME}" \
        --arg mass_password "${MASS_PASSWORD}" \
        '{options: {app_ip: $app_ip, mass_ip: $mass_ip, mass_port: $mass_port, mass_token: $mass_token, mass_username: $mass_username, mass_password: $mass_password}}')"

    if curl -sf -X POST \
        -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" \
        -H "Content-Type: application/json" \
        -d "${PATCH_BODY}" \
        http://supervisor/addons/self/options >/dev/null 2>&1; then
        bashio::log.info "Saved auto-detected address(es) to the Configuration tab."
    else
        bashio::log.warning "Could not save auto-detected address(es) back to Configuration — will re-detect next boot."
    fi
fi

export TZ
TZ="$(bashio::supervisor.timezone)"
bashio::log.info "Timezone set from Home Assistant Supervisor: ${TZ}"

bashio::log.info "Starting Bose SoundTouch Hybrid..."
cd /app || exit 1
exec node server.js
